# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [16]:
import torch

Construct a 5x3 matrix, uninitialized

In [17]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.1814e-34, 0.0000e+00, 1.4714e-43],
        [1.5414e-43, 1.6255e-43, 5.6052e-44],
        [1.6816e-43, 4.4842e-44, 6.0256e-44],
        [4.4842e-44, 1.6956e-43, 5.7453e-44],
        [7.2436e+22, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [18]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1910, 0.5620, 0.9977],
        [0.0792, 0.0044, 0.2520],
        [0.6579, 0.8552, 0.4862],
        [0.2889, 0.3035, 0.6627],
        [0.1570, 0.8796, 0.7956]])


Get its size

In [19]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [20]:
x[1:3] = 2
print(x)

tensor([[0.1910, 0.5620, 0.9977],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2889, 0.3035, 0.6627],
        [0.1570, 0.8796, 0.7956]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [47]:
x_norm = torch.Tensor(2,17)
print(x_norm)
x_float = torch.FloatTensor(3,1)
print()
print(x_float)

x_long = torch.LongTensor(5,2,1)
print()
x_long[:] = 7
print(x_long)

x_byte = torch.ByteTensor(5,)
x_byte[1:4] = 1
print()
print(x_byte)





tensor([[3.6639e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.1706e-34, 0.0000e+00, 1.3637e-35, 0.0000e+00, 3.8315e-16],
        [4.5724e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

tensor([[1.1814e-34],
        [0.0000e+00],
        [2.3694e-38]])

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

tensor([128,   1,   1,   1,   0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [42]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6589, 0.7928, 1.0094],
        [2.4261, 2.9951, 2.0323],
        [2.1814, 2.3065, 2.4088],
        [1.2208, 0.5437, 0.6937],
        [0.5062, 1.7465, 0.9988]])


### 2.2 Addition: syntax 2

In [43]:
print(torch.add(x, y))

tensor([[0.6589, 0.7928, 1.0094],
        [2.4261, 2.9951, 2.0323],
        [2.1814, 2.3065, 2.4088],
        [1.2208, 0.5437, 0.6937],
        [0.5062, 1.7465, 0.9988]])


### 2.3 Addition: giving an output tensor

In [44]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6589, 0.7928, 1.0094],
        [2.4261, 2.9951, 2.0323],
        [2.1814, 2.3065, 2.4088],
        [1.2208, 0.5437, 0.6937],
        [0.5062, 1.7465, 0.9988]])


### 2.4 Addition: in-place

adds `x`to `y`

In [45]:
y.add_(x)
print(y)

tensor([[0.6589, 0.7928, 1.0094],
        [2.4261, 2.9951, 2.0323],
        [2.1814, 2.3065, 2.4088],
        [1.2208, 0.5437, 0.6937],
        [0.5062, 1.7465, 0.9988]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [48]:
print(x[:, 1])

tensor([0.5620, 2.0000, 2.0000, 0.3035, 0.8796])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [50]:
# Assignment 1
print(y * x)

tensor([[0.1258, 0.4456, 1.0070],
        [4.8522, 5.9902, 4.0647],
        [4.3627, 4.6131, 4.8177],
        [0.3527, 0.1650, 0.4597],
        [0.0795, 1.5363, 0.7946]])


In [52]:
# Assignment 2
y.mul(x)

tensor([[0.1258, 0.4456, 1.0070],
        [4.8522, 5.9902, 4.0647],
        [4.3627, 4.6131, 4.8177],
        [0.3527, 0.1650, 0.4597],
        [0.0795, 1.5363, 0.7946]])

In [54]:
# Assignment 3
print( y/x)

tensor([[3.4504, 1.4108, 1.0117],
        [1.2130, 1.4975, 1.0162],
        [1.0907, 1.1533, 1.2044],
        [4.2254, 1.7916, 1.0469],
        [3.2237, 1.9855, 1.2555]])


In [58]:
x1 = torch.rand(2,4)
y1 = torch.rand(4,2)

x1.matmul(y1)

tensor([[0.8000, 0.6129],
        [0.7804, 0.5441]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [61]:
a = torch.ones(5)
print(a)


tensor([1., 1., 1., 1., 1.])


In [62]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [63]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [64]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [70]:
a_ten = torch.Tensor(5,2)
a_ten.numpy()
a = torch.from_numpy(a)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")